Repository konveyor/forklift-operator, pull requests merged in 2021-11, with the labels that each got.

#179 Update CRDs with fix for BZ#2012564
  bundle/manifests/forklift.konveyor.io_migrations.yaml
  bundle/manifests/forklift.konveyor.io_plans.yaml
Labels: v2.2.0/yes

#182 Undo Plan precopy status change
  bundle/manifests/forklift.konveyor.io_migrations.yaml
  bundle/manifests/forklift.konveyor.io_plans.yaml
Labels: v2.2.0/yes

#184 Bug 2024153: Make PRECOPY_INTERVAL a managed setting in operator
  roles/forkliftcontroller/defaults/main.yml
  roles/forkliftcontroller/templates/configmap-controller.yml.j2
  roles/forkliftcontroller/templates/deployment-controller.yml.j2
Labels: v2.2.0/yes

#186 Bug 1942651: Enable vSphere incremental backup by default
  roles/forkliftcontroller/defaults/main.yml
  roles/forkliftcontroller/templates/deployment-controller.yml.j2
Labels: v2.2.0/yes

#189 Use must gather image envvar
  roles/forkliftcontroller/defaults/main.yml
  roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2
Labels: bug, v2.2.0/yes

#190 Use must-gather image environment variable in must-gather-api deployment
  roles/forkliftcontroller/defaults/main.yml
  roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2
Labels: bug

#191 Replace DEFAULT_IMAGE with MUST_GATHER_IMAGE
  roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2
Labels: v2.2.0/yes

#194 Bug 2026702: Do not override controller and validation service configmaps
  roles/forkliftcontroller/tasks/main.yml
Labels: bug

#195 Allow setting debug mode for must-gather-api
  roles/forkliftcontroller/defaults/main.yml
  roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2
Labels: enhancement, v2.2.0/yes

#196 Allow setting debug mode for must-gather-api
  roles/forkliftcontroller/defaults/main.yml
  roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2
Labels: bug

#197 Bug 2026702: Do not initialize empty data structure on validation config map
  roles/forkliftcontroller/tasks/main.yml
  roles/forkliftcontroller/templates/configmap-validation.yml.j2
Labels: bug, v2.2.0/yes
